// <auto-generated />
using GraphQLProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLProject.Migrations
{
    [DbContext(typeof(GraphQLDbContext))]
    [Migration("20250812050458_SeedMenusTable")]
    partial class SeedMenusTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQLProject.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cheese Pizza",
                            Name = "Pizza",
                            Price = 10.99
                        },
                        new
                        {
                            Id = 2,
                            Description = "Veggie Pizza",
                            Name = "Pizza",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pepperoni Pizza",
                            Name = "Pizza",
                            Price = 14.99
                        },
                        new
                        {
                            Id = 4,
                            Description = "Chicken Pizza",
                            Name = "Pizza",
                            Price = 16.989999999999998
                        },
                        new
                        {
                            Id = 5,
                            Description = "Margherita Pizza",
                            Name = "Pizza",
                            Price = 11.99
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
